config/routes.rb
Rails.application.routes.draw do

  root to: 'artists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "artists" => "artists#index"
  # get "artists/:id" => "artists#show", as: :artist
  resources :artists do
    resources :songs, only: [:new, :create, :destroy]
end
namespace :api do
    resources :artists do
      resources :songs
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy

    validates :first_name,  presence: true
    validates :last_name,   presence: true
    validates :genre,       presence: true

    def fullname
      "#{first_name} #{last_name}"
    end


end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :title,           presence: true
  validates :album,           presence: true
  validates :video_url,       presence: true
end

app/controllers/api/artists_controller.rb
class Api::ArtistsController < ApplicationController
  def index
    render status: 200, json: {
      artists: Artist.all
    }.to_json
  end
  def show
    artist = Artist.find(params[:id])

    render status: 200, json: {
      artist: artist
    }.to_json
  end
  def destroy
    artist = Artist.find(params[:id])
    artist.destroy

    render status: 200, json: {
      message: "Artist successfully deleted"
    }.to_json
  end
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController

  def index
    render status: 200, json: {
      songs: Song.all
    }.to_json
  end

  def show
    song = Song.find(params[:id])

    render status: 200, json: {
      song: song
    }.to_json
  end
  
  def destroy
    song = Song.find(params[:id])
    song.destroy

    render status: 200, json: {
      message: "Song successfully deleted"
    }.to_json
  end

  private
  def song_params
    params.require(:song).permit(:title, :album, :video_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

        def index
            @artists = Artist.all
        end

        def show
            @artist = Artist.find(params[:id])
        end



        def new
          @artist = Artist.new
        end

        def create
              @artist = Artist.new(artist_params)

          if  @artist.save
              redirect_to artists_path(params[:artist_id]), notice: "artist successfully created"
          else
              render :new
          end
        end

        def update
            if @artist.update(artist_params)

            end
            redirect_to artist_path(params[:artist_id]), notice: "artist successfully updated"
            else
            render :update
        end


        def destroy
          @artist = Artist.find(params[:id])

          @artist.destroy

          redirect_to artists_path
        end


        private

        def artist_params
              params.require(:artist).permit(:first_name, :last_name, :genre)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController


      def index;
      end
      def show
              @song = Song.find(params[:id])

      end
      def create
              @song = Song.new(song_params)

              if @song.save
                redirect_to artist_path(@songs), notice: "artist successfully created"
              else
                  render :new
              end
      end

      def new
              @song = Song.new
      end


              def create
                @song = Song.create(song_params.merge(artist_id: params[:artist_id]))

                respond_to do |format|
                  if @song.save
                    format.html { redirect_to artist_path(params[:artist_id]), notice: 'Song was successfully created.' }
                    format.json { render :show, status: :created, location: @Song }
                  else
                    format.html { redirect_to artist_songs_path }
                    format.json { render json: @Song.errors, status: :unprocessable_entity }
                  end
                end
              end




      def destroy
              @song = Song.find(params[:id])

              @song.destroy
              respond_to do |format|
                    format.html { redirect_to artist_path(params[:artist_id]), notice: 'Song was deleted.'}
                    format.json { head :no_content }
                  end 
      end


      private
      def set_artist
              @song = Artist.find(params[:artist_id])
      end

      def song_params
              params.require(:song).permit(:title, :album, :video_url)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for [@artist] do |f| %>

<div class="form-group">
  <label>Artist first name</label>
  <%= f.text_area :first_name, placeholder: "What is the Artists' first name?", class: "form-control" %>
</div>

<div class="form-group">
  <label>Artist last</label>
  <%= f.text_area :last_name, placeholder: "What is the Artists' last name?", class: "form-control" %>
</div>
<div class="form-group">
  <label>Artist Genre</label>
  <%= f.text_area :genre, placeholder: "What Genre?", class: "form-control" %>
</div>

  <%= f.submit (@artist.new_record? ? "Create" : "Update") %>
  <label>Photos</label>

  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

<%end%>

app/views/artists/index.html.erb
<!-- app/views/Artists/index.html.erb -->

<% @artists.each do |artist| %>
<div class="container">
  <%= image_tag artist.image, class:"image"%>
  <div class="overlay">
    <div class="text"><button><%=link_to artist.fullname, artist_path(artist.id)%></button></div>
  </div>
</div>
<%end%>





<button type="button" class="btn btn-secondary btn-lg btn-block"><%= link_to "!WELCOME!" %></button>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= form_for @artist do |f| %>
<div class="form-group">
  <label>Artist first name</label>
  <%= f.text_area :first_name, placeholder: "What is the Artists' first name?", class: "form-control" %>
</div>

<div class="form-group">
  <label>Artist last</label>
  <%= f.text_area :last_name, placeholder: "What is the Artists' last name?", class: "form-control" %>
</div>
<div class="form-group">
  <label>Artist Genre</label>
  <%= f.text_area :genre, placeholder: "What Genre?", class: "form-control" %>
</div>

  <%= f.submit "Create" %>
<% end %>

app/views/artists/show.html.erb
<hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading"><h1><%= @artist.fullname %></h1><span class="text-muted"></span></h2>
          <p class="lead"><p>Artist genre: <%= @artist.genre %></p></p>
        </div>
        <div class="col-md-5">
          <h2><%= image_tag @artist.image, class:"showimage" %></h2>
        </div>
      </div>



<h3><b>Songs</b></h3>

<h5><a href="#" id="SongsDelete">Delete all songs</a></h5>
      <table class="table table-striped" id="songList">
        <%= render @artist.songs %>
      </table>
<hr />
<h4><b>Add a song for this artist?</b></h4>
<button type="button" class="btn btn-secondary"><%= link_to "New Song", new_artist_song_path(@artist.id) %></button>

<hr>
<button type="button" class="btn btn-outline-info"><%= link_to "Delete artist", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" } %></button>
<button type="button" class="btn btn-outline-info"><%= link_to "Back to Artists", root_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
  <%= render "shared/navbar" %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= yield %>
  </div>

  <body>


<br><br>
<hr>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="javascript/artist.js"></script>
</body>

</html>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <span class="btn btn-default">Delete</span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

app/views/songs/_form.html.erb
<%= form_for @song, url: artist_songs_path do |f| %>


<div class="form-group">
  <label>Song Name</label>
  <%= f.text_area :title, placeholder: "What is the title of the song?", class: "form-control" %>
</div>

<div class="form-group">
  <label>Song Album</label>
  <%= f.text_area :album, placeholder: "What is the Songs album?", class: "form-control" %>
</div>

<div class="form-group">
  <label>Video URLe</label>
  <%= f.text_area :video_url, placeholder: "Where can people check the video?", class: "form-control" %>
</div>
  <%= f.submit (@song.new_record? ? "Create" : "Update") %>

<% end %>

app/views/songs/_song.html.erb
<tr class="song" data-id="<%= song.id %>">

  <td>
    <label for="song-<%= song.id %>">Song title:<pre><%= song.title %></pre>Album<pre><%=song.album%></pre>Video_url<pre><%=song.video_url%></pre></label>
    <pre><%= link_to "Delete", artist_song_path(song.artist, song), method: :delete, data: { confirm: "Are you sure?" } %></pre>
  </td>
</tr>

app/views/songs/new.html.erb
What is the title of the song<%= form_for @song, url: artist_songs_path do |f| %>


<div class="form-group">
  <label>Song Name</label>
  <%= f.text_area :title, placeholder: "What is the title of the song?", class: "form-control" %>
</div>

<div class="form-group">
  <label>Song Album</label>
  <%= f.text_area :album, placeholder: "What album is the song on?", class: "form-control" %>
</div>

<div class="form-group">
  <label>Video URL</label>
  <%= f.text_area :video_url, placeholder: "Where can I check the video?", class: "form-control" %>
</div>
  <%= f.submit (@song.new_record? ? "Create" : "Update") %>

<% end %>